apiVersion: apps/v1
kind: Deployment
metadata:
  name: declarative-deployment
  labels:
    app: express.js
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: test-app
          image: enliberte/test_app
          ports:
            - containerPort: 3000