apiVersion: v1
kind: Pod
metadata:
  name: testapp
  namespace: myapps
  labels:
    app: express
spec:
  containers:
    - name: test-app
      image: enliberte/test_app
      ports:
        - name: test-app-port
          containerPort: 3000
          protocol: TCP