apiVersion: v1
kind: Service
metadata:
  namespace: myapps
  name: myservice
spec:
  type: NodePort
  selector:
    app: express
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000